### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Agazed** [sainttx/Auctions#1]
http://pastebin.com/1P1j6m6c

Been getting that error sometimes when a player tries to auction something. Only happens once in a while, not sure why. The whole plugin locks up and a restart fixes it.

**Comment by sainttx** [comment]
This error should be fixed in v2.2.0

**Comment by Agazed** [comment]
Forgot I posted on here. This was caused by my CombatLog plugin not removing NPC's from the correct world.
