### ISSUE TITLE
Support for 1.10

### ISSUE THREAD

**Issue by TheChampTF** [sainttx/Auctions#7]
Hey

Sadly it's broken http://paste.yu8.me/?da4fa7b0eaed5e1d#7cEjL2YbZOxbTiNvg9UAPVHDjKo3rsRaFApSQg2JV9Q=

Also looks like it don’t like PerWorld, anything there can be done?

**Comment by JamieSinn** [comment]
Confirming
https://gist.github.com/andrewkm/617078576db24506656203f1e40e2c71
@sainttx

**Comment by andrewkm** [comment]
Can confirm, dead.

**Comment by andris155** [comment]
https://github.com/mkremins/fanciful/commit/39beb57decbb2541abdb113f7d7267e5f90b6e80

**Comment by JamieSinn** [comment]
Just need to update Fanciful to 0.3.5

**Comment by ghost** [comment]
Fixed and still works on 1.10.2+ , thanks!
